# This file contains uv configuration for FormatPilot extension
# It demonstrates the use of uv as package manager

[project]
name = "formatpilot-extension"
version = "0.1.0"
description = "VS Code extension for text format conversion"
requires-python = ">=3.7"

dependencies = [
    "formatpilot>=0.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
